name: CI

on:
  pull_request:
    paths-ignore:
      - .github/workflows/tf-apply.yaml
      - .github/workflows/tf-plan.yaml
      - '**README.md'
      - '**docs/**'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI tests
        uses: ./.github/actions/ci-test
        with:
          working_directory: app/hellofincra
