name: OpenTofu Apply

on:
  push:
    paths-ignore:
      - .github/workflows/tf-apply.yaml
      - .github/workflows/tf-plan.yaml
      - '**README.md'
      - '**docs/**'
    branches:
      - main


defaults:
  run:
    working-directory: .


jobs:
  opentofu-plan:
    name: OpenTofu Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::001983765648:role/gha-terraform-admin

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color
        continue-on-error: true


  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: opentofu-plan
    if: success() # Only proceed if opentofu-plan job succeeds

    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: sysadmin-exe
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Opentofu Apply"
          issue-body: "Please approve or deny the deployment."

  opentofu-apply:
    name: OpenTofu Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [manual-approval, opentofu-plan]
    permissions:
      id-token: write
      contents: read
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::281138642656:role/gha-cloudnova-infra

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Apply
        if: github.event_name == 'push'
        id: apply
        run: tofu apply -auto-approve -no-color